
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Booked_Tickets_Details
{

    public int ticketID { get; set; }

    public string placeName { get; set; }

    public Nullable<System.DateTime> timeStart { get; set; }

    public Nullable<System.DateTime> timeEnd { get; set; }

    public Nullable<decimal> price { get; set; }

    public string fullName { get; set; }

    public string address { get; set; }

    public string eventName { get; set; }

    public string seatPlace { get; set; }

    public Nullable<int> isBooked { get; set; }

    public string email { get; set; }

}

}
