
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Customer_Ticket_Details
{

    public int ticketId { get; set; }

    public string fullName { get; set; }

    public string email { get; set; }

    public string eventName { get; set; }

    public string placeName { get; set; }

    public string eventAddress { get; set; }

    public System.DateTime timeStart { get; set; }

    public System.DateTime timeEnd { get; set; }

    public decimal price { get; set; }

    public string seatLocation { get; set; }

}

}
