
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Customer_Details
{

    public int Customer_ID { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public int Phone_Number { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public int Postcode { get; set; }

    public System.DateTime Date_Of_Birth { get; set; }

    public System.DateTime Date_Created { get; set; }

}

}
