

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CustomerDatabaseEntities : DbContext
{
    public CustomerDatabaseEntities()
        : base("name=CustomerDatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer_Details> Customer_Details { get; set; }

    public virtual DbSet<Employee_Details> Employee_Details { get; set; }

    public virtual DbSet<Ticket_Details> Ticket_Details { get; set; }

    public virtual DbSet<Event_Details> Event_Details { get; set; }

}

}

