
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Details
{

    public int Event_ID { get; set; }

    public string Event_Title { get; set; }

    public string Event_Description { get; set; }

    public System.DateTime Event_Start { get; set; }

    public System.DateTime Event_End { get; set; }

    public int Capacity { get; set; }

    public byte[] Event_Picture { get; set; }

    public string Event_Location { get; set; }

    public string Event_Address { get; set; }

}

}
