
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Details
{

    public int eventID { get; set; }

    public string eventTitle { get; set; }

    public string eventDescription { get; set; }

    public System.DateTime eventStart { get; set; }

    public System.DateTime eventEnd { get; set; }

    public int capacity { get; set; }

    public byte[] eventPicture { get; set; }

    public string eventLocation { get; set; }

    public string eventAddress { get; set; }

    public byte[] eventLayout { get; set; }

    public Nullable<bool> showOnHomePage { get; set; }

    public string eventGenre { get; set; }

}

}
