
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Guest_Transaction
{

    public int transactionId { get; set; }

    public string address { get; set; }

    public string email { get; set; }

    public decimal totalPrice { get; set; }

    public string eventName { get; set; }

    public string eventAddress { get; set; }

    public string fullName { get; set; }

}

}
