
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Ticket_Details
{

    public int TicketID { get; set; }

    public string EventTitle { get; set; }

    public System.DateTime EventStart { get; set; }

    public System.DateTime EventEnd { get; set; }

    public string SeatLetter { get; set; }

    public int SeatNumber { get; set; }

    public decimal Price { get; set; }

}

}
