
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ssample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Ticket_Details
{

    public int ticketId { get; set; }

    public string eventTitle { get; set; }

    public System.DateTime eventStart { get; set; }

    public System.DateTime eventEnd { get; set; }

    public string seatLocation { get; set; }

    public decimal price { get; set; }

}

}
